[project]
name = "vase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "anyio>=4.11.0",
    "colorama>=0.4.6",
    "httpx>=0.28.1",
    "keyring>=25.6.0",
    "orjson>=3.11.3",
    "psutil>=7.1.0",
    "pyjwt>=2.10.1",
    "pystray>=0.19.5",
    "semantic-version>=2.10.0",
    "tomlkit>=0.13.3",
    "watchfiles>=1.1.1",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.16.0",
]
