import asyncio
from collections.abc import AsyncGenerator
from typing import Tuple

import anyio

from vase import api
from vase.journal.base import JournalSource


class _JournalType(JournalSource, api.Journal):
    pass

class JournalMultiplexer:
    def __init__(self, journals: list[_JournalType]):
        self.journals = journals

    async def events(
            self,
    ) -> AsyncGenerator[Tuple[api.Journal, api.JournalEvent], None]:
        """
        This function returns a generator providing events as they are generated by elite.
        It is the main interface between processors and the Journal files.
        """
        send, recv = anyio.create_memory_object_stream(32)

        async def pump(s, q):
            async for e in s.events():
                await q.send(e)

        with asyncio.TaskGroup() as tg:
            async with send:
                for journal in self.journals:
                    tg.start_soon(pump, journal, send)
            async for item in recv:
                yield item
